### ISSUE TITLE
push/pull to/from codebase file path

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3837]
# Problem Description

Right now if you have two separate local codebases, it's a huge pain to get code from one of them into the other.

The easiest way is to push a namespace to Share and then pull it into the other codebase. But this solution is a bummer for a number of reasons.

- It's slow. Something that could be completely local is now using a remote server as a middle-person.
- ~Share currently doesn't support private namespaces/projects, so you can only do it with public-facing code.~ No longer true.
- You might not actually want this to become a namespace and add clutter to your Share namespaces.

# Current Workaround

You can currently achieve the desired outcome, but it's a hassle.

1. Google "git orphan repo" and stare at the results in confusion for a few minutes.
2. Google "git bare repo" because that's actually what you meant.
3. Create a new local git bare repo: `git init --bare /tmp/temp_repo.git`
5. Search the Unison docs for the syntax to push using the git protocol.
6. Google "git file protocol how many slashes"
7. Push to the local bare repo from codebase 1: `.> push git(file:///tmp/temp_repo.git).someNamespace .someNamespace`
8. Pull from the local bare repo in codebase 2: `.> pull git(file:///tmp/temp_repo.git).someNamespace .someNamespace`
9. (bonus points) delete the temporary bare repo

# Proposed Solution

Add support for a local file protocol to ucm. Something like:

```
.> push file(/home/me/code/unisonCodebase1).someNamespace .someNamespace

.> pull file(/home/me/code/unisonCodebase2).someNamespace .someNamespace
```

If the implementation of this command wants to create a bare repo behind the scenes that's fine by me.

## Controversial Decisions

I'm assuming that the path should be to the parent directory that _contains_ the `.unison` directory, because that's how other codebase paths generally work in UCM right now. Some users might expect to point directly to the SQLite file or the `.unison` directory?

**Comment by ceedubs** [comment]
Implementing this could provide one option to work around #3314 .

**Comment by aryairani** [comment]
@ceedubs Does it help that you don't have to use `file://`? you Should be able to 
```
$ git init --bare /tmp/temp_repo
.> push git(/tmp/temp_repo).someNamespace .someNamespace
.> pull git(/tmp/temp_repo).someNamespace .someNamespace
```

**Comment by ceedubs** [comment]
@aryairani Slightly. Thanks for the tip. But I still think that my proposal would improve the ergonomics a lot. Manually creating a bare repo isn't very user-friendly (or discoverable).

**Comment by aryairani** [comment]
I was gonna suggest that you don't need a bare repo either, but I guess you do:
```
  Synced 6856 entities.
  I couldn't push to the repository at /tmp/foo ; the error was:
  remote: error: refusing to update checked out branch: refs/heads/trunk        
    remote: error: By default, updating the current branch in a non-bare repository        
    remote: is denied, because it will make the index and work tree inconsistent        
    remote: with what you pushed, and will require 'git reset --hard' to match        
    remote: the work tree to HEAD.        
    remote: 
    remote: You can set the 'receive.denyCurrentBranch' configuration variable        
    remote: to 'ignore' or 'warn' in the remote repository to allow pushing into        
    remote: its current branch; however, this is not recommended unless you        
    remote: arranged to update its work tree to match what you pushed in some        
    remote: other way.        
    remote: 
    remote: To squelch this message and still keep the default behaviour, set        
    remote: 'receive.denyCurrentBranch' configuration variable to 'refuse'.     
```
