### ISSUE TITLE
hashFiles(...) is returning empty strings in CI??

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4029]
e.g. https://github.com/unisonweb/unison/actions/runs/5072635396/jobs/9110605904
```
Cache not found for input keys: stack-0_ubuntu-20.04--7a87252b74e2502d4d9ee70726fb10a148876812, stack-0_ubuntu-20.04-, stack-0_ubuntu-20.04
```

but the definition is
```yaml
        with:
          path: ~/.stack
          # Main cache key: commit hash. This should always result in a cache miss...
          # So when loading a cache we'll always fall back to the restore-keys,
          # which should load the most recent cache via a prefix search on the most
          # recent branch cache.
          # Then it will save a new cache at this commit sha, which should be used by
          # the next build on this branch.
          key: stack-0_${{matrix.os}}-${{hashFiles('stack.yaml')}}-${{github.sha}}
          # Fall-back to use the most recent cache for the stack.yaml, or failing that the OS
          restore-keys: |
            stack-0_${{matrix.os}}-${{hashFiles('stack.yaml')}}
            stack-0_${{matrix.os}}
```

So why is `hashFiles()` giving an empty string?
https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles doesn't have an example of loading a single file, though that would be nice.
